name: speech_to_text
version: 5.6.1
description: Local patched copy of speech_to_text
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text_platform_interface: ^2.4.0
  json_annotation: any
  clock: any

flutter:
  uses-material-design: true
