// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-n8iQ_05M6shCfKR1VVQwYCYbDNkaY7I',
    appId: '1:1067543596698:web:33b363b5a95c05a88ad923',
    messagingSenderId: '1067543596698',
    projectId: 'lensaaurora',
    authDomain: 'lensaaurora.firebaseapp.com',
    storageBucket: 'lensaaurora.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8IwVWTSfHAILBOzMVhmFTq6Ue0MxfB5Q',
    appId: '1:1067543596698:android:fc1094eea059ce6f8ad923',
    messagingSenderId: '1067543596698',
    projectId: 'lensaaurora',
    storageBucket: 'lensaaurora.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJZw33Y09e-AXhwEO4KH9BiNSxGqhrZEU',
    appId: '1:1067543596698:ios:9a015ed0c505a7dc8ad923',
    messagingSenderId: '1067543596698',
    projectId: 'lensaaurora',
    storageBucket: 'lensaaurora.firebasestorage.app',
    iosBundleId: 'com.example.lensaaurora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJZw33Y09e-AXhwEO4KH9BiNSxGqhrZEU',
    appId: '1:1067543596698:ios:9a015ed0c505a7dc8ad923',
    messagingSenderId: '1067543596698',
    projectId: 'lensaaurora',
    storageBucket: 'lensaaurora.firebasestorage.app',
    iosBundleId: 'com.example.lensaaurora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-n8iQ_05M6shCfKR1VVQwYCYbDNkaY7I',
    appId: '1:1067543596698:web:03297c0f8ae535cd8ad923',
    messagingSenderId: '1067543596698',
    projectId: 'lensaaurora',
    authDomain: 'lensaaurora.firebaseapp.com',
    storageBucket: 'lensaaurora.firebasestorage.app',
  );
}
